package rage7.greendaosample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BIKE".
 */
public class Bike {

    private Long id;
    private String modelname;
    private String modelLinkRewrite;
    private String popularity;
    private String exShowroomPrice;
    private String engineCapacity;

    public Bike() {
    }

    public Bike(Long id) {
        this.id = id;
    }

    public Bike(Long id, String modelname, String modelLinkRewrite, String popularity, String exShowroomPrice, String engineCapacity) {
        this.id = id;
        this.modelname = modelname;
        this.modelLinkRewrite = modelLinkRewrite;
        this.popularity = popularity;
        this.exShowroomPrice = exShowroomPrice;
        this.engineCapacity = engineCapacity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getModelname() {
        return modelname;
    }

    public void setModelname(String modelname) {
        this.modelname = modelname;
    }

    public String getModelLinkRewrite() {
        return modelLinkRewrite;
    }

    public void setModelLinkRewrite(String modelLinkRewrite) {
        this.modelLinkRewrite = modelLinkRewrite;
    }

    public String getPopularity() {
        return popularity;
    }

    public void setPopularity(String popularity) {
        this.popularity = popularity;
    }

    public String getExShowroomPrice() {
        return exShowroomPrice;
    }

    public void setExShowroomPrice(String exShowroomPrice) {
        this.exShowroomPrice = exShowroomPrice;
    }

    public String getEngineCapacity() {
        return engineCapacity;
    }

    public void setEngineCapacity(String engineCapacity) {
        this.engineCapacity = engineCapacity;
    }

}
