package rage7.greendaosample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import rage7.greendaosample.Bike;

import rage7.greendaosample.BikeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bikeDaoConfig;

    private final BikeDao bikeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bikeDaoConfig = daoConfigMap.get(BikeDao.class).clone();
        bikeDaoConfig.initIdentityScope(type);

        bikeDao = new BikeDao(bikeDaoConfig, this);

        registerDao(Bike.class, bikeDao);
    }
    
    public void clear() {
        bikeDaoConfig.getIdentityScope().clear();
    }

    public BikeDao getBikeDao() {
        return bikeDao;
    }

}
